# Generated by Django 4.2.7 on 2023-12-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact_sex_alter_contact_age_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
